services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/myDB
      - VALKEY_HOST=valkey 
      - VALKEY_PORT=6379

    depends_on:
      - mongo
      - valkey
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  valkey: 
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    
volumes:
 mongo_data:
 valkey_data:
