services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/myDB
      - REDIS_URL=redis://valkey:6379
      - JWT_ACCESS_SECRET=docker_compose_jwt_access_secret_key
      - JWT_REFRESH_SECRET=docker_compose_jwt_refresh_secret_key
    depends_on:
      - mongo
      - valkey
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  valkey: 
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_URL=redis://valkey:6379
    volumes:
      - valkey_data:/data
    
volumes:
 mongo_data:
 valkey_data:
